{{- if .Values.cronjobs.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-refresh-pubsub
spec:
  schedule: "0 0 * * *"  # Run at midnight every day
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: refresh-pubsub
            image: curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - |
              curl -X POST http://{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:8080/refresh_subscriptions
          restartPolicy: OnFailure
{{- end }}
